// export const BASE_URL = "https://api.nsrice.in/";
export const BASE_URL = "https://api.cravehub.store/";
export const USERS_URL = "/api/users";
export const CATEGORY_URL = "/api/category";
export const PRODUCT_URL = "/api/products";
export const UPLOAD_URL = "/api/upload";
export const ORDERS_URL = "/api/orders";
export const PAYPAL_URL = "/api/config/paypal";
export const COUPONS_URL = '/api/coupons';
